version: '3.7'
services:
  postgres:
    image: postgres:latest
    ports:
      - '3300:3306'
    volumes:
      - ./data/var/lib/postgres
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=9mREsvXDs9Gk89Ef
